apiVersion: v1
kind: ServiceAccount
metadata:
  name: login-sa
  namespace: travelportal
---
apiVersion: v1
kind: Secret
metadata:
  name: login-sa-token
  namespace: travelportal
  annotations:
    kubernetes.io/service-account.name: login-sa
type: kubernetes.io/service-account-token
