apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.serviceAccountName" . }}-token
  annotations:
    kubernetes.io/service-account.name: {{ include "todo-app.serviceAccountName" . }}
type: kubernetes.io/service-account-token